# Generated by Django 5.0.6 on 2024-06-28 09:59

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('brand_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fueltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='call_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car_sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Reject', 'Reject'), ('accept', 'Accept')], default=('Reject', 'Reject'), max_length=60)),
                ('seller_name', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('kilometer', models.IntegerField()),
                ('owners', models.IntegerField()),
                ('features', ckeditor.fields.RichTextField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.brand')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.color')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.fueltype')),
            ],
        ),
        migrations.CreateModel(
            name='Car_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(upload_to='')),
                ('image4', models.ImageField(upload_to='')),
                ('year', models.IntegerField()),
                ('kilometer', models.IntegerField()),
                ('owners', models.IntegerField()),
                ('features', ckeditor.fields.RichTextField(null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.color')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.fueltype')),
                ('price_range', models.ForeignKey(default='null', on_delete=django.db.models.deletion.DO_NOTHING, to='car_app.range')),
            ],
        ),
    ]
